version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/stack_utils
hooks:
  AfterInstall:
   - location: scripts/dependency_installations.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: root